Fix build with Clang on 32-bit systems
__builtin_smulll_overflow doesn't work on 32-bit systems yet,
causing undefined reference to __mulodi4.

https://llvm.org/bugs/show_bug.cgi?id=14469